
project:
  type: default


format:
  html:
    toc: true
    toc-depth: 5
    number-sections: false
    toc-location: left
    toc-expand: false
    smooth-scroll: true
    code-fold: true
    self-contained: true   # <- IMPORTANT

jupyter: python3

